---
- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Set "cron" state "started" and enabled "yes"
  ansible.builtin.service:
    name: cron
    state: started
    enabled: true
