---
name: Ansible Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Create CI-specific vault password file in workspace
        run: |
          echo "ci_dummy_placeholder_password" > ${{ github.workspace }}/.ansible_vault_password_for_ci
          chmod 600 ${{ github.workspace }}/.ansible_vault_password_for_ci

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: ${{ github.workspace }}/.ansible_vault_password_for_ci
